### ISSUE TITLE
download of precompiled jar for version 2.0-M04 doesn't work

### ISSUE THREAD

**Issue by kaazoo** [neo4j-contrib/authentication-extension#11]
http://dist.neo4j.org.s3.amazonaws.com/authentication-extension/authentication-extension-2.0-M04-1.0-SNAPSHOT-server-plugin.zip

gives me:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>762ADE37290EB642</RequestId><HostId>iFV1/fygxINag2M6nb7Vxclho0lcJaMxIvEdFq1TyZ+mFIcDVE5X7B2r1xLoLhns</HostId></Error>
```

**Comment by jexp** [comment]
Sorry, this is the right link:

http://dist.neo4j.org/authentication-extension/authentication-extension-2.0.0-M04-1.0-SNAPSHOT.jar

**Comment by kaazoo** [comment]
thx
