### ISSUE TITLE
server can't start in 2.0.0-RC1

### ISSUE THREAD

**Issue by buzzfrog** [neo4j-contrib/authentication-extension#16]
I get the following dialog window when I try to start the server:

Starting Neo4j Server failed: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-1835453513@efd27de2==org.neo4j.server.web.NeoServletContainer,-1,false

/dag

**Comment by jexp** [comment]
Yep this plugin has not been updated to 2.0-RC1, usually it is more sensible to use an external proxy with auth to secure your server.

If you really need it, ping me again and I'll push an updated version.

**Comment by jexp** [comment]
Ok will provide the version, but for the long term it makes more sense with an http proxy: nginx, apache, iis?

**Comment by buzzfrog** [comment]
You don't need to do this for my blog post. In that I use neo4j 1.8 and this version of your plugin work. I was more thinking if this is not a good practice at all and I should change it to proxy.
In my example I use a predefined Ubuntu dist. (Sorry, my ignorance, but I think that it has apache installed.) I'm a Windows guy, so this is new territory.
/dag

Date: Tue, 3 Dec 2013 00:59:12 -0800

**Comment by jexp** [comment]
Updated to RC1

**Comment by jexp** [comment]
Regarding the proxy: does this help you: 
http://joewhite86.wordpress.com/2013/05/29/secure-neo4j-webadmin-using-http-auth-and-ssl/

**Comment by buzzfrog** [comment]
Thanks./dag

Date: Tue, 3 Dec 2013 01:33:17 -0800
