### ISSUE TITLE
Spring Data, Neo4j, configure port and path for webadmin.

### ISSUE THREAD

**Issue by SannyStark** [neo4j-contrib/authentication-extension#17]
Hi guys. I have some question about configure neo4j at spring. I have project, where i deploy embeded neo4j server, and configure webadmin server. But sometimes i need hide this  webadmin from another users,when i deploying it to server. How can i change port and path for this tools. (db/data and /webadmin).

**Comment by jexp** [comment]
Please ask the question in the Neo4j google group or on stack-overflow.

You can change the port in `conf/neo4j-server.properties`

No way to change the path I think, but there are some config options in `neo4j-server.properties` too.

**Comment by SannyStark** [comment]
Thanks for quick answer.
