### ISSUE TITLE
Exclude specific path/url or pattern from basic authentication ?

### ISSUE THREAD

**Issue by kwent** [neo4j-contrib/authentication-extension#20]
There is a way to exclude a specific path/url or pattern from basic authentication ?

**Comment by jexp** [comment]
You can modify the source code to determine where the filter is placed (registration) or add a path exclusion to the Auth filter itself.

**Comment by kwent** [comment]
Could you give me an example where and how to modify ?

**Comment by jexp** [comment]
See here: https://github.com/neo4j-contrib/authentication-extension/blob/2.1/src/main/java/org/neo4j/server/extension/auth/AuthenticationExtensionInitializer.java#L82
