### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by Jesterovskiy** [neo4j-contrib/authentication-extension#26]
Maybe this not fully related to authentication-extension, but I`ll describe my situation here.
I have neo4j instance with authentication-extension and SSL support. I use wildcard certificate, for example *.domain.com and try to access neo4j by IP address. Issue is: hostname does not match the server certificate. Can I access neo4j by db.domain.com and use authentication-extension? Or I need somehow configure nginx to use SSL port and then redirect to /auth? Thank you for any help =)

**Comment by hoffmaaxe** [comment]
If you use a wildcard certificate and try to connect by ip, it is usual, that your browsers warns you, because the ip address doesn't match a subdomain of your domain. Have you tried to connect the server by db.domain.com?

**Comment by Jesterovskiy** [comment]
You are right, I'm added db.domain.com to `/etc/hosts` and now works properly =)
