### ISSUE TITLE
Does this Authentication header works when contacting to a neo4j server remotely?

### ISSUE THREAD

**Issue by sreelathakoye** [neo4j-contrib/authentication-extension#29]
Hello,

Iam new to this neo4j, and i have a scenario where i should give remote access to a neo4j server with credentials.
So iam trying to download jar file
add these 3 lines into neo4j-server.properties
org.neo4j.server.webserver.address=xx.xxx.xx.xx
org.neo4j.server.credentials=username:password
org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.auth=/auth

But when i try http://xx.xxx.xxx.xx:7518/auth
it prompts me for password and username, but when i provide, ideally what i need is it should get browser screen of neo4j, that is what is needed. Does this authentication extension provides that?
I mean i need authentication to be provided to remote server for browser page(http://xx.xxx.xxx.xx:7518/browser) . after correct authentication it should redirect to browser page.
I badly need help in this.
Any pointers would be very helpful.

Thanks 
Sreelatha.

**Comment by jexp** [comment]
Yep it should work, make sure to use the **right version for your neo4j-instance**.

What exactly doesn't work? Can you check the `data/log/*.log` files of your sever for any error messages?

**Comment by sreelathakoye** [comment]
Hello Jexp,

Thanks for all your support.
Actually i was trying it with VNC server, with 1 GB RAM so it was very slow, and i miss took it as not working.
For authentication for browser i simply put that as 
org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.auth=/*
This worked.

Thanks you,
Sreelatha.
