### ISSUE TITLE
Spring Data and authentication-extension

### ISSUE THREAD

**Issue by pawelantczak** [neo4j-contrib/authentication-extension#30]
Hello.
Do you know guys, if there is a way to use this plugin in conjunction with Spring Data neo4j?
Since spring uses http to connect standalone neo, technically it is not big deal.
Question is, how can I pass user credentials to Spring.
Thanks.

**Comment by jexp** [comment]
In your spring config you can configure your SpringRestGraphDatabase with url, user,password

Von meinem iPhone gesendet

**Comment by pawelantczak** [comment]
Indeed. I overlooked constructor parameters. Thanks.
Reference: http://docs.spring.io/spring-data/neo4j/docs/current/api/org/springframework/data/neo4j/rest/SpringRestGraphDatabase.html
