### ISSUE TITLE
Upload jar file

### ISSUE THREAD

**Issue by elado** [neo4j-contrib/authentication-extension#4]
Can you please upload a compiled jar file ready to install?

Thanks!

**Comment by emourant** [comment]
Some useful documentation on building a jar wouldn't go a miss either.

**Comment by jexp** [comment]
The jars are here: https://github.com/neo4j-contrib/authentication-extension/downloads

Unfortunately github has discontinued that feature, see: https://github.com/blog/1302-goodbye-uploads

So we have to put them somewhere else ...

for now:
https://dl.dropbox.com/u/14493611/authentication-extension-1.9-SNAPSHOT-1.0-SNAPSHOT.jar

**Comment by jexp** [comment]
Updated the dropbox file.

**Comment by jexp** [comment]
Added download section to readme:

https://github.com/neo4j-contrib/authentication-extension/blob/1.9/Readme.md#download-of-precompiled-jars

**Comment by ghost** [comment]
the links return "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."
I guess this is related to the region of the bucket if I remember well there is something like you need to include the region in the URL.
The Dropbox link works though.
