### ISSUE TITLE
migrate to neo4j-contrib

### ISSUE THREAD

**Issue by akollegger** [neo4j-contrib/authentication-extension#5]
The "neo4j" github organization should only contain projects that are part of the Neo4j distribution (or part of the supporting infrastructure). This project is an open-sourced part of Neo Technology's cloud work, which is generally useful for anyone with a similar need for adding basic auth to Neo4j. 

This repository should be forked to "neo4j-contrib".

**Comment by simpsonjulian** [comment]
Done.
